-- =======================================================
-- SCRIPT COMPLETO DE BASE DE DATOS Y AUDITORÍA EN SUPABASE
-- Ejecutar en el SQL Editor de Supabase (https://app.supabase.com)
-- =======================================================

-- Habilitar extensión UUID si no existe
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Tabla principal de Análisis Químicos
CREATE TABLE IF NOT EXISTS analisis_quimicos (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  fecha DATE NOT NULL,
  hora TIME NOT NULL,
  punto_muestreo TEXT NOT NULL,
  parametros JSONB NOT NULL,
  usuario_email TEXT NOT NULL,
  rol TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Tabla de Trazabilidad / Auditoría Paralela de Análisis Químicos
CREATE TABLE IF NOT EXISTS auditoria_quimica (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  usuario_email TEXT NOT NULL,
  rol TEXT NOT NULL,
  accion TEXT NOT NULL,
  punto_muestreo TEXT NOT NULL,
  detalle JSONB
);

-- 3. Tabla de Bitácoras Operativas
CREATE TABLE IF NOT EXISTS bitacoras (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio TEXT,
  fecha DATE,
  turno TEXT,
  operador TEXT,
  jefe_turno TEXT,
  estado TEXT DEFAULT 'borrador',
  contenido JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Tabla de Personal y Estado de Turnos (turnos_personal)
CREATE TABLE IF NOT EXISTS turnos_personal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio TEXT UNIQUE NOT NULL,
  rotacion TEXT,
  jefe_turno TEXT,
  operador_sala TEXT,
  operador_terreno TEXT,
  generacion_promedio NUMERIC,
  costo_marginal NUMERIC,
  pot_espera NUMERIC,
  hay_contingencia BOOLEAN DEFAULT FALSE,
  motivo_contingencia TEXT,
  detalle_contingencia TEXT,
  resumen_reemplazos TEXT,
  actualizado_el TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Deshabilitar RLS para permitir lecturas y escrituras directas desde el cliente Supabase anon
ALTER TABLE analisis_quimicos DISABLE ROW LEVEL SECURITY;
ALTER TABLE auditoria_quimica DISABLE ROW LEVEL SECURITY;
ALTER TABLE bitacoras DISABLE ROW LEVEL SECURITY;
ALTER TABLE turnos_personal DISABLE ROW LEVEL SECURITY;
